spring.application.name=station_lavage

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DB}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.mvc.view.prefix:/jsp/
spring.mvc.view.suffix:.jsp

server.port=${PORT:8080}