spring.application.name=station_lavage

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://mamadisory2000:mamadi10___@cluster0.amjqrxf.mongodb.net/?appName=Cluster0}
spring.data.mongodb.database=${MONGODB_DB:stationdb}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:550723132061-opaumta3va5arfq8aiqbp84k9j79gabu.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}

spring.mvc.view.prefix:/jsp/
spring.mvc.view.suffix:.jsp

server.port=${PORT:8080}